-- ============================================================
-- SIGEX — V8: Seed catálogo de ambientes FCyT UMSS (SAGAA 2-2026)
-- Códigos de aula extraídos de horarios oficiales FCyT.
-- Fuente: sagaa.fcyt.umss.edu.bo + docs/Catalogo_Ambientes_FCyT_UMSS.txt
-- Idempotente: no duplica por nombre (uq_ambiente_nombre).
-- ============================================================

INSERT INTO public.ambiente (nombre, ubicacion)
SELECT v.nombre, v.ubicacion
FROM (VALUES
    -- Aulas numéricas
    ('606', 'FCyT UMSS'),
    ('607', 'FCyT UMSS'),
    ('608', 'FCyT UMSS'),
    ('609', 'FCyT UMSS'),
    ('612', 'FCyT UMSS'),
    ('614', 'FCyT UMSS'),
    ('615', 'FCyT UMSS'),
    ('616', 'FCyT UMSS'),
    ('617', 'FCyT UMSS'),
    ('618', 'FCyT UMSS'),
    ('620', 'FCyT UMSS'),
    ('621', 'FCyT UMSS'),
    ('622', 'FCyT UMSS'),
    ('623', 'FCyT UMSS'),
    ('624', 'FCyT UMSS'),
    ('640', 'FCyT UMSS'),
    ('642', 'FCyT UMSS'),
    ('651', 'FCyT UMSS'),
    ('652', 'FCyT UMSS'),
    ('660', 'FCyT UMSS'),
    ('661', 'FCyT UMSS'),
    ('668', 'FCyT UMSS'),
    ('670', 'FCyT UMSS'),
    -- Variantes con letra / laboratorio
    ('608A', 'FCyT UMSS'),
    ('608B', 'FCyT UMSS'),
    ('609A', 'FCyT UMSS'),
    ('617B', 'FCyT UMSS'),
    ('617C', 'FCyT UMSS'),
    ('625C', 'FCyT UMSS'),
    ('625D', 'FCyT UMSS'),
    ('644A', 'FCyT UMSS'),
    ('667A', 'FCyT UMSS'),
    ('667B', 'FCyT UMSS'),
    ('669A', 'FCyT UMSS'),
    ('671A', 'FCyT UMSS'),
    ('671B', 'FCyT UMSS'),
    ('671C', 'FCyT UMSS'),
    ('681A', 'FCyT UMSS'),
    ('681B', 'FCyT UMSS'),
    ('681L7', 'FCyT UMSS — laboratorio'),
    ('681L9ME', 'FCyT UMSS — laboratorio'),
    ('682A', 'FCyT UMSS'),
    ('682B', 'FCyT UMSS'),
    ('682L0IN', 'FCyT UMSS — laboratorio Informática'),
    ('682L1', 'FCyT UMSS — laboratorio'),
    ('682L2', 'FCyT UMSS — laboratorio'),
    ('682L3', 'FCyT UMSS — laboratorio'),
    ('682L4', 'FCyT UMSS — laboratorio'),
    ('682L6IN', 'FCyT UMSS — laboratorio Informática'),
    ('682L7IN', 'FCyT UMSS — laboratorio Informática'),
    ('682L8IN', 'FCyT UMSS — laboratorio Informática'),
    ('683J', 'FCyT UMSS'),
    ('684B', 'FCyT UMSS'),
    ('684L0', 'FCyT UMSS — laboratorio'),
    ('684L6', 'FCyT UMSS — laboratorio'),
    ('684L7', 'FCyT UMSS — laboratorio'),
    ('684L8', 'FCyT UMSS — laboratorio'),
    -- Bloque 690–693 (muy usado en Informática / Sistemas)
    ('690A', 'FCyT UMSS'),
    ('690B', 'FCyT UMSS'),
    ('690C', 'FCyT UMSS'),
    ('690D', 'FCyT UMSS'),
    ('690E', 'FCyT UMSS'),
    ('690MAT', 'FCyT UMSS — Matemática'),
    ('691A', 'FCyT UMSS'),
    ('691B', 'FCyT UMSS'),
    ('691C', 'FCyT UMSS'),
    ('691D', 'FCyT UMSS'),
    ('691E', 'FCyT UMSS'),
    ('691F', 'FCyT UMSS'),
    ('692A', 'FCyT UMSS'),
    ('692B', 'FCyT UMSS'),
    ('692C', 'FCyT UMSS'),
    ('692D', 'FCyT UMSS'),
    ('692E', 'FCyT UMSS'),
    ('692F', 'FCyT UMSS'),
    ('692G', 'FCyT UMSS'),
    ('692H', 'FCyT UMSS'),
    ('693A', 'FCyT UMSS'),
    ('693B', 'FCyT UMSS'),
    ('693C', 'FCyT UMSS'),
    ('693D', 'FCyT UMSS'),
    -- Ambientes con nombre / labs / auditorios
    ('A808', 'FCyT UMSS'),
    ('AUDCIV', 'FCyT UMSS — auditorio Civil'),
    ('AUDELEK', 'FCyT UMSS — auditorio Eléctrica/Electrónica'),
    ('AUDIND', 'FCyT UMSS — auditorio Industrial'),
    ('AUDINF', 'FCyT UMSS — auditorio Informática'),
    ('AULVIR', 'FCyT UMSS — aula virtual'),
    ('CADCAM', 'FCyT UMSS — laboratorio CAD/CAM'),
    ('CAE', 'FCyT UMSS — laboratorio CAE'),
    ('CAMPO', 'FCyT UMSS — campo'),
    ('FISCOM', 'FCyT UMSS — Física computacional'),
    ('GABI', 'FCyT UMSS'),
    ('HERBARI', 'FCyT UMSS — herbario'),
    ('INFDEP', 'FCyT UMSS — departamento Informática'),
    ('INFLAB', 'FCyT UMSS — laboratorio Informática'),
    ('L813', 'FCyT UMSS — laboratorio'),
    ('LABMAT', 'FCyT UMSS — laboratorio Matemática'),
    ('LABMETR', 'FCyT UMSS — laboratorio metrología'),
    ('MAGCIV', 'FCyT UMSS — aula magna Civil'),
    ('MATDEP', 'FCyT UMSS — departamento Matemática'),
    ('MECDEP', 'FCyT UMSS — departamento Mecánica'),
    ('MEMIDIR', 'FCyT UMSS — MEMI'),
    ('MICBIO', 'FCyT UMSS — microbiología')
) AS v(nombre, ubicacion)
WHERE NOT EXISTS (
    SELECT 1 FROM public.ambiente a WHERE a.nombre = v.nombre
);

COMMENT ON TABLE public.ambiente IS
    'Catálogo de ambientes de evaluación (FCyT UMSS / SAGAA). Seed V8.';
