import { useEffect, useState } from 'react'
import { AlertTriangle, BookOpen, CalendarDays, Check, CheckCircle2, ChevronLeft, Clock3, History, LoaderCircle, MapPin, ShieldCheck, UserRound, X } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import PanelLayout from '../../components/layout/PanelLayout'
import { autorizarIngreso, obtenerContextoControl, obtenerHistorialControl, obtenerTiposIncidencia } from '../../services/controlIngresoService'
import type { AutorizarIngresoResultado, ContextoControlIngreso, RegistroControlIngreso, TipoIncidencia } from '../../types/controlIngreso'

const CHECKS = ['Identidad contrastada', 'Material permitido verificado', 'Normas comunicadas']
const card = 'rounded-2xl border border-[#DCE5F2] bg-white p-4 shadow-sm sm:p-5'

function Title({ n, icon, text }: { n: number; icon: React.ReactNode; text: string }) {
  return <div className="mb-4 flex items-center gap-2 border-b border-[#E6EDF8] pb-3"><b className="grid h-5 w-5 place-items-center rounded-full bg-[#0439D9] text-[10px] text-white">{n}</b><span className="text-[#0439D9]">{icon}</span><h2 className="text-xs font-extrabold uppercase tracking-wide text-[#15213B]">{text}</h2></div>
}

export default function ControlIngresoPage() {
  const nav = useNavigate(), p = useParams()
  const idEstudiante = Number(p.idEstudiante), idExamen = Number(p.idExamen)
  const valid = Number.isInteger(idEstudiante) && Number.isInteger(idExamen)
  const [ctx, setCtx] = useState<ContextoControlIngreso | null>(null)
  const [types, setTypes] = useState<TipoIncidencia[]>([]), [typeId, setTypeId] = useState<number | null>(null)
  const [obs, setObs] = useState(''), [incident, setIncident] = useState(''), [checks, setChecks] = useState<string[]>([])
  const [loading, setLoading] = useState(valid), [saving, setSaving] = useState(false), [error, setError] = useState(valid ? '' : 'Identificadores inválidos.')
  const [result, setResult] = useState<AutorizarIngresoResultado | null>(null)
  const [historyOpen, setHistoryOpen] = useState(false), [historyLoading, setHistoryLoading] = useState(false), [history, setHistory] = useState<RegistroControlIngreso[]>([])

  useEffect(() => {
    if (!valid) return
    Promise.all([obtenerContextoControl(idEstudiante, idExamen), obtenerTiposIncidencia()]).then(([c, t]) => { setCtx(c); setTypes(t); setTypeId(t[0]?.id ?? null) }).catch(() => setError('No se pudo cargar la información del control.')).finally(() => setLoading(false))
  }, [idEstudiante, idExamen, valid])

  const openHistory = async () => { setHistoryOpen(true); setHistoryLoading(true); try { setHistory(await obtenerHistorialControl(idEstudiante, idExamen)) } finally { setHistoryLoading(false) } }
  const submit = async () => { setSaving(true); setError(''); try { setResult(await autorizarIngreso({ idEstudiante, idExamen, observaciones: obs, verificacionesAdicionales: checks, incidencias: incident.trim() && typeId ? [{ idTipoIncidencia: typeId, descripcion: incident.trim() }] : [] })) } catch { setError('No se pudo registrar el control. Intenta nuevamente.') } finally { setSaving(false) } }

  return <PanelLayout compactDesktop title="CONTROL DE INGRESO" description="Verifica la información y registra la autorización de ingreso al examen.">
    <main className="min-h-full bg-[#F4F6F9] px-3 pb-28 pt-4 sm:px-6 min-[960px]:pb-8"><div className="mx-auto max-w-6xl">
      <button onClick={() => nav(-1)} className="mb-3 inline-flex items-center text-xs font-bold text-[#0439D9]"><ChevronLeft size={15}/>Volver</button>
      {loading && <div role="status" className={`${card} p-12 text-center`}><LoaderCircle className="mx-auto animate-spin text-[#0439D9]"/>Cargando...</div>}
      {error && <div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
      {!loading && ctx && <div className="space-y-4">
        <section className={card}><div className="flex flex-col justify-between gap-4 min-[760px]:flex-row min-[760px]:items-center"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-extrabold text-[#15213B]">{ctx.asignatura}</h1><span className="rounded-md bg-[#E8F0FF] px-2 py-1 text-[10px] font-bold text-[#0439D9]">EX-{ctx.idExamen}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${ctx.habilitado ? 'bg-[#DDF8E9] text-[#079455]' : 'bg-[#FFE6EA] text-[#D92D4A]'}`}>{ctx.habilitado ? 'Habilitado' : 'No habilitado'}</span></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-[#61718A]"><span className="flex items-center gap-1 rounded-full bg-[#F4F7FB] px-3 py-1.5"><CalendarDays size={13}/>{ctx.fecha}</span><span className="flex items-center gap-1 rounded-full bg-[#F4F7FB] px-3 py-1.5"><Clock3 size={13}/>{ctx.horaInicio} · {ctx.duracionMinutos} min</span><span className="flex items-center gap-1 rounded-full bg-[#F4F7FB] px-3 py-1.5"><MapPin size={13}/>{ctx.ambiente}</span></div></div><button onClick={openHistory} className="flex min-h-10 items-center justify-center gap-2 rounded-lg border border-[#C8D5E8] px-4 text-sm font-bold text-[#0439D9]"><History size={16}/>Historial del control</button></div></section>
        <section className="grid gap-4 min-[800px]:grid-cols-[.8fr_1.2fr]">
          <article className={card}><Title n={1} icon={<UserRound size={16}/>} text="Información del estudiante"/><div className="flex items-center gap-3"><b className="grid h-12 w-12 place-items-center rounded-full bg-[#E8F0FF] text-[#0439D9]">{ctx.estudiante.split(' ').slice(0,2).map(x=>x[0]).join('')}</b><div><p className="font-bold text-[#15213B]">{ctx.estudiante}</p><p className="text-xs text-[#7586A0]">Estudiante registrado</p></div></div><dl className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-[#F7F9FC] p-3 text-xs"><div><dt className="text-[#8492A8]">Código universitario</dt><dd className="font-bold">{ctx.codigoSis}</dd></div><div><dt className="text-[#8492A8]">Carnet / CI</dt><dd className="font-bold">{ctx.documento}</dd></div></dl></article>
          <article className={card}><Title n={2} icon={<BookOpen size={16}/>} text="Normas del examen"/><div className="space-y-2">{ctx.normasGenerales.map((x,i)=><div key={x} className="flex gap-3 rounded-lg border border-[#E4EAF3] p-3 text-xs"><b className="grid h-5 w-5 shrink-0 place-items-center rounded bg-[#FFF5D9] text-[#C57A00]">{i+1}</b>{x}</div>)}</div>{ctx.normasParticulares.length>0&&<div className="mt-3 border-t pt-3"><b className="text-[11px] uppercase text-[#087F73]">Normas particulares</b>{ctx.normasParticulares.map(x=><p key={x} className="mt-2 rounded-lg bg-[#EAFBF7] p-3 text-xs text-[#087F73]">{x}</p>)}</div>}</article>
        </section>
        {(!ctx.habilitado||ctx.ingresoRegistrado)&&<section className="rounded-xl border border-[#FFBFC9] bg-[#FFF2F4] p-4 text-[#C7193F]"><div className="flex gap-2"><AlertTriangle size={20}/><div><b>No se puede autorizar el ingreso</b><p className="text-sm">{ctx.ingresoRegistrado?'El ingreso ya fue registrado para este examen.':ctx.motivoInhabilitacion||'El estudiante no está habilitado.'}</p></div></div></section>}
        {!ctx.ingresoRegistrado&&<section className={card}><Title n={3} icon={<ShieldCheck size={16}/>} text="Registro y verificaciones del control"/><div className="grid gap-5 min-[800px]:grid-cols-2"><div><label className="text-xs font-bold">Observaciones generales</label><textarea value={obs} onChange={e=>setObs(e.target.value)} rows={4} maxLength={1000} className="mt-2 w-full rounded-lg border border-[#C8D5E8] p-3 text-sm" placeholder="Registra observaciones relevantes del control..."/></div><fieldset><legend className="text-xs font-bold">Verificaciones adicionales</legend><div className="mt-2 space-y-2">{CHECKS.map(x=><label key={x} className={`flex cursor-pointer gap-3 rounded-lg border p-3 text-sm ${checks.includes(x)?'border-[#0439D9] bg-[#F1F5FF] text-[#0439D9]':'border-[#DCE5F2]'}`}><input type="checkbox" checked={checks.includes(x)} onChange={()=>setChecks(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x])}/>{x}</label>)}</div></fieldset></div><div className="mt-5 border-t pt-4"><label className="text-xs font-bold">Incidencia detectada <i className="font-normal text-[#8492A8]">(opcional)</i></label><div className="mt-2 grid gap-2 min-[700px]:grid-cols-[.8fr_1.2fr]"><select aria-label="Tipo de incidencia" value={typeId??''} onChange={e=>setTypeId(Number(e.target.value))} className="rounded-lg border border-[#C8D5E8] bg-white p-3 text-sm">{types.map(t=><option key={t.id} value={t.id}>{t.nombre}</option>)}</select><textarea value={incident} onChange={e=>setIncident(e.target.value)} rows={2} className="rounded-lg border border-[#C8D5E8] p-3 text-sm" placeholder="Opcional: describe la incidencia..."/></div></div></section>}
        {!ctx.ingresoRegistrado&&<div className="fixed inset-x-0 bottom-0 z-20 flex justify-end gap-2 border-t bg-white/95 p-3 shadow-lg min-[960px]:static min-[960px]:rounded-xl min-[960px]:border"><button onClick={()=>nav(-1)} className="rounded-lg border px-5 text-sm font-bold">Cancelar</button><button onClick={submit} disabled={saving||!!result} className={`flex min-h-11 flex-1 items-center justify-center gap-2 rounded-lg px-5 text-sm font-bold text-white min-[600px]:flex-none ${ctx.habilitado?'bg-[#0439D9]':'bg-[#D92D4A]'}`}><CheckCircle2 size={17}/>{saving?'Registrando...':ctx.habilitado?'Autorizar ingreso':'Registrar control denegado'}</button></div>}
      </div>}
    </div></main>
    {historyOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#DCE9FA]/80 p-3" role="dialog" aria-modal="true" aria-label="Historial del control"><section className="max-h-[88vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><header className="sticky top-0 flex justify-between border-b bg-white p-4"><div><h2 className="font-extrabold">Historial del control realizado</h2><p className="text-xs text-[#7586A0]">Autorizaciones y denegaciones registradas</p></div><button aria-label="Cerrar historial" onClick={()=>setHistoryOpen(false)}><X/></button></header><div className="space-y-3 p-4">{historyLoading&&<p>Cargando...</p>}{history.map(r=><article key={r.idRegistro} className="rounded-xl border p-4"><div className="flex justify-between"><b className={r.resultado==='AUTORIZADO'?'text-green-700':'text-red-700'}>{r.resultado}</b><time className="text-xs text-[#7586A0]">{new Date(r.fechaHora).toLocaleString()}</time></div><p className="mt-2 text-sm font-bold">Personal de control: {r.usuarioControl}</p>{r.causa&&<p className="text-sm text-red-700">Causa: {r.causa}</p>}{r.observaciones&&<p className="text-sm">Observaciones: {r.observaciones}</p>}{r.verificacionesAdicionales.map(x=><p key={x} className="flex items-center gap-1 text-xs text-[#61718A]"><Check size={12}/>{x}</p>)}</article>)}</div></section></div>}
    {result&&<div className="fixed inset-0 z-[60] grid place-items-center bg-[#DCE9FA]/80 p-4" role="dialog" aria-modal="true" aria-label="Resultado del control"><section className="w-full max-w-md rounded-2xl bg-white p-6 text-center shadow-2xl"><div className={`mx-auto grid h-14 w-14 place-items-center rounded-full ${result.autorizado?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>{result.autorizado?<CheckCircle2/>:<AlertTriangle/>}</div><h2 className="mt-4 text-xl font-extrabold">{result.autorizado?'Ingreso autorizado':'Ingreso denegado'}</h2><p className="mt-2 text-sm text-[#61718A]">{result.autorizado?`Registrado por ${result.autorizadoPor} a las ${new Date(result.fechaHoraIngreso).toLocaleString()}.`:result.causa}</p><button onClick={()=>setResult(null)} className="mt-6 min-h-11 w-full rounded-lg bg-[#0439D9] font-bold text-white">Cerrar</button></section></div>}
  </PanelLayout>
}
