name: Validar Pull Requests Multi-OS

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-backend:
    # Definimos la matriz con los 3 sistemas operativos
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    # Asignamos la variable de la matriz al sistema virtual
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Cambia a tu versión
          distribution: 'temurin'
      - name: Ejecutar tests del Backend
        working-directory: ./backend
        run: ./mvnw test
        shell: bash # Forza el uso de bash para que el wrapper ./mvnw funcione en Windows

  test-frontend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        working-directory: ./frontend
        run: npm ci
      - name: Ejecutar tests del Frontend
        working-directory: ./frontend
        run: npm run test
