name: Validar Pull Requests Multi-OS

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-backend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # Esto hace que los tests sean mucho más rápidos guardando las dependencias
      - name: Ejecutar tests del Backend
        working-directory: ./backend
        run: mvn test # Usamos mvn nativo en lugar del wrapper local
        shell: bash

  test-frontend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # o la versión que estés usando
          
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'pnpm'
          cache-dependency-path: ./frontend/pnpm-lock.yaml
          
      - name: Instalar dependencias
        working-directory: ./frontend
        # usamos install simple porque quizás aún no has subido tu pnpm-lock.yaml
        run: pnpm install
        
      - name: Ejecutar tests del Frontend
        working-directory: ./frontend
        run: pnpm run test
